kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: kennb-dockerhub
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: kennb-dockerhub
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: kennb-dockerhub
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgAqQaSUhyDUVwy6HGDVuHHbcnJpTNwuo+xTKqs+oPVT/zQVIdDEkPEt1DjX5ZFDPHCuVB6S3sjjlBifoWKkeqJK289zW2ISnCEUZSez1znn2Dcx8YZIFW8EhsHTlVYnT4+Oz2ORdPCfPuqrHoDZ9JWBMVIs9NwS85Ucks6jHzkRWgbNlykYpfDhxVK2lW5AlP3WNmgbGxiEDTHusfh+g+BDgthoH26ZK6asUXzhDCwepjeWdsi6Pgsrv2vg9Dx9X/dD7w435iM761pZ+Pw8pkGgXBJYpGVAdgOYAeSkGBl5b3WZZ//gehzVSG+E2XqLvkHAc5K0go/EBwGgmcYfxDZ63KGjjKALKbFREfIYCoCmc4E4+o2up2dHeqizwSFqSiMZmzUvhQ/1PuLTIgsG/o25PSjAspumyjdQXtLhnn21uyiy2T+2Dqwnj4iiQRaRDiUYKUn9lmqbBwPJeKN0jaPiSV5fxONdGW4TGkAOnEBft++rnODfutqQ0TZb1uUbcMyheRw5ZHy6Z9C3S9ZlGmi41GqdI9fSRheQNFHNJIz1idWXtON49GskHU0HgFgyLw8Ak00L2g/qwKRsxL0ZkgWveZbPEENJDPFIcC6Cb6B9MGeZTkP3UE85lPB6VzqzUaTNoHrw+hPCIZphEtenQoKC2rwBW+hgeSSS05i0uJCtkA+CitAI44kAR16WNaH4s2db8amVte9J1q7UEYtNOq8Y6A==
