gitops-runtime:
  global:
    codefresh:
      accountId: 66fdee985027eb6793702ddf
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: cf-gitops
